# Generated by Django 6.0 on 2025-12-10 19:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(max_length=100)),
                ('id_alumno', models.IntegerField(blank=True, null=True)),
                ('ticket', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Archivo de imagen')),
            ],
        ),
    ]
