# Generated by Django 6.0 on 2025-12-12 22:18

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('invitados_min', models.IntegerField(default=0)),
                ('invitados_max', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('prorroga', 'Prórroga')], default='pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Comprobante')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='tickets.alumno')),
            ],
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
