# Generated by Django 6.0 on 2025-12-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alumno_pago_delete_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('al_corriente', 'Al Corriente'), ('prorroga', 'Prórroga')], default='pendiente', max_length=20),
        ),
    ]
