# Generated by Django 6.0 on 2025-12-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_alumno_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='monto',
        ),
        migrations.AddField(
            model_name='pago',
            name='cantidad_boletos',
            field=models.IntegerField(default=1, verbose_name='Cantidad de Boletos'),
        ),
    ]
